Repository un-ts/synckit, pull requests merged in 2025-05, with the labels that each got.

#237 chore: bump all (dev)Dependencies
  package.json
  yarn.lock
Labels: dependencies, internal

#240 refactor: target ES2020 to drop `tslib` dependency
  .changeset/sweet-spies-shout.md
  package.json
  tsconfig.json
  yarn.lock
Labels: enhancement, dependencies

#217 fix: unexpected null pointer exception due to race condition
  .changeset/shiny-kids-check.md
  package.json
  src/helpers.ts
  test/reliability.spec.ts
  test/types-d.cts
  test/worker-identity.js
Labels: bug

#246 chore: bump all (dev)Dependencies
  .changeset/soft-chefs-hang.md
  .github/workflows/autofix.yml
  .size-limit.json
  eslint.config.js
  package.json
  src/helpers.ts
  test/types-d.cts
  yarn.lock
Labels: dependencies
